[project]
name = "wearable-prototype"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.7",
    "pillow>=12.0.0",
    "scikit-learn>=1.7.2",
    "ultralytics>=8.3.217",
]
